version: 2

build:
  os: "ubuntu-22.04"
  tools:
    dart: "2.16.0"  # Specify the Dart SDK version you need

dependencies:
  # Install Flutter and Dart dependencies
  - type: system
    apt:
      packages:
        - libglu1-mesa
        - curl

  # Install Flutter SDK
  - type: git
    repository: https://github.com/flutter/flutter.git
    submodules: true

  # Run Flutter doctor to ensure environment setup
  - type: shell
    commands:
      - export PATH="$HOME/flutter/bin:$PATH"
      - flutter doctor

  # Install Flutter and Dart dependencies from pubspec.yaml
  - type: shell
    commands:
      - flutter pub get